### ISSUE TITLE
Unable to install gtest

### ISSUE THREAD

**Issue by jslee02** [dartsim/homebrew-dart#3]
I tried to install gtest using Homebrew on Mac 10.9.2 but failed. Here is the error message:

```
brew install https://raw.github.com/dartsim/homebrew-dart/master/gtest.rb
######################################################################## 100.0%
==> Downloading http://googletest.googlecode.com/files/gtest-1.6.0.zip
Already downloaded: /Library/Caches/Homebrew/gtest-1.6.0.zip
==> cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/gtest/1.6.0 -DCMAKE_BUILD_T
==> make install
make: *** No rule to make target `install'.  Stop.

READ THIS: https://github.com/Homebrew/homebrew/wiki/troubleshooting
```

Did I something wrong?

**Comment by jslee02** [comment]
gtest-1.7 can be installed by:
```
brew install ros/deps/gtest
```

**Comment by scpeters** [comment]
I think the gtest formulae can be installed manually, but as I said before in this thread, it is not recommended to use an installed version of gtest. In fact, the homebrew tool will ignore gtest dependencies (see [blacklist.rb](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/blacklist.rb#L44-L47)) specified by a formula. That's probably why `brew install dart` doesn't install gtest.

I can advise about the recommended way to do use gtest.

**Comment by jslee02** [comment]
I tried to create gtest formulae manually but, as you said, couldn't with this error message `gtest is blacklisted for creation`. We should add in gtest source as Gazebo did, I think.

**Comment by jslee02** [comment]
Resolved by https://github.com/dartsim/dart/pull/315.

Thanks @scpeters !
