### ISSUE TITLE
Homebrew/science has been deprecated

### ISSUE THREAD

**Issue by jeremydwong** [dartsim/homebrew-dart#46]
homebrew/science/libccd was deleted from homebrew/science in commit 224eed91:
  Deprecate Homebrew/homebrew-science (https://github.com/Homebrew/homebrew-science/issues/6616)

**Comment by jslee02** [comment]
Thanks for the report. This should be resolved once https://github.com/Homebrew/homebrew-core/pull/22359 is merged. Once it's merged, all the formula in this repo will be updated accordingly.

**Comment by jslee02** [comment]
This is resolved by https://github.com/dartsim/homebrew-dart/pull/49.
