### ISSUE TITLE
master does not contain dartsim6

### ISSUE THREAD

**Issue by SlightlyCyborg** [dartsim/homebrew-dart#64]

**Comment by jslee02** [comment]
`dartsim6` is migrated to homebrew-core. Now you can install `dartsim6` as
```
$ brew update
$ brew install dartsim
```

This repo will maintain only the old versions of DART.

**Comment by SlightlyCyborg** [comment]
Ok. Great!!! This is more of a problem with the documentation site then.

**Comment by jslee02** [comment]
Yeah, the documentation should be updated. :sweat_smile: (see: https://github.com/dartsim/homebrew-dart/issues/65)
