### ISSUE TITLE
Migrate the users of the dartsim/dart/ipopt formula to use the ipopt formula from homebrew core

### ISSUE THREAD

**Issue by traversaro** [dartsim/homebrew-dart#76]
Ipopt has been migrated to be hosted on GitHub (https://list.coin-or.org/pipermail/ipopt/2019-April/004635.html), and its new website is https://coin-or.github.io/Ipopt . For this reason, it could make sense to migrate also the ipopt homebrew formula to use GitHub's release tarballs and repo .
~The issue arose because coin-or.org is currently down (see https://github.com/robotology/human-dynamics-estimation/pull/125#issuecomment-500394450), but even if they eventually fix it, it probably make sense in general to switch to the "primary" repo.~
In particular, it seems that the SVN repo is no longer updated, so to get an actually working `--head` option, we would need to switch to the new github git repo.

cc @lrapetti

**Comment by jslee02** [comment]
I just realized that ipopt is already in the main repo!: https://github.com/Homebrew/homebrew-core/pull/38270, https://github.com/Homebrew/homebrew-core/pull/40696, https://github.com/Homebrew/homebrew-core/pull/40698

[The formula is still using coin.or.org for tarballs](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ipopt.rb#L4) but uses GitHub for `--head` option. It would make more sense to create an issue or send a pull request to the main repo if needed.

**Comment by traversaro** [comment]
> I just realized that ipopt is already in the main repo!: Homebrew/homebrew-core#38270, Homebrew/homebrew-core#40696, Homebrew/homebrew-core#40698

Cool, I never realized that. Thanks for the pointer!

**Comment by jslee02** [comment]
If the formula works for you then I'm happy to remove `ipopt` from this tap. I'm testing for DART now.

**Comment by traversaro** [comment]
> If the formula works for you then I'm happy to remove ipopt from this tap. I'm testing for DART now.

Great. I think we need to migrate a bunch of documentation and CI scripts, so if we could keep the formula in this tap up for a few weeks, it would be great.

**Comment by traversaro** [comment]
(Title updated)

**Comment by traversaro** [comment]
Hi @jslee02 , we migrated away from the `dartsim/ipopt` in most relevant repos, feel free to remove it from the tap, thanks for maintaining it for all this time!

**Comment by jslee02** [comment]
https://github.com/dartsim/homebrew-dart/pull/81 is created to remove `dartsim/ipopt`.
